'use client'
import Head from "next/head";
import Homepage from "@/components/HomePage";
import SideBarMenu from "@/components/SideBarMenu"
import RemarkableGoals from "@/components/RemarkableGoals";
import Cookies from "js-cookie";

export default function Analytics({children}) {
  if (sessionStorage.getItem('token') == null || Cookies.get('token') == null) {
    // Redireccionar al usuario a la página de login si no tiene token
    window.location.href = '/login';
    // Puedes retornar null o cualquier otro contenido mientras se redirige
    return null;
  }
    return (
        <div className="#DC0A2D">
          <Head>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/pro.ico" />
          </Head>
          <div>
          <RemarkableGoals/>
        <SideBarMenu />
        </div>
        
      </div>
          
      );
    }