'use client'
import Head from "next/head";
import Homepage from "@/components/HomePage";
import SideBarMenu from "@/components/SideBarMenu"
import RemarkableGoals from "@/components/RemarkableGoals";

export default function Analytics({children}) {
    return (
        <div className="#DC0A2D">
          <Head>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/pro.ico" />
          </Head>
          <div>
          <RemarkableGoals/>
        <SideBarMenu />
        </div>
        
      </div>
          
      );
    }