"use client";

import Head from "next/head";

import SpecificPokemon from "@/components/SpecificPokemon";

export default function Specific({}) {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </Head>

      <div>
        <SpecificPokemon />
      </div>
    </div>
  );
}
