'use client';

import Head from "next/head";

import Pokemon from "@/components/Pokemon";
import SearchBar from "@/components/SearchBar";
import SideBarMenu from "@/components/SideBarMenu";



export default function Pokedex({children}) {
    return (
        <div >
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap"
  rel="stylesheet"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
      </Head>
      <SideBarMenu/>
      
        <div>
          <Pokemon />
        </div>
    
      </div>
    );
  }