import Head from "next/head";
import Pokemon from "@/components/Pokemon";

export default function Pokedex({children}) {
    return (
        <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pro.ico" />
        </Head>
        <div>
          <Pokemon />
        </div>
    
      </div>
    );
  }