'use client'
import 'app/global.css'
import Head from "next/head";
import SetHome from "@/components/SetHome";
import Cookies from '@/components/Cookies';
import React from 'react';
import CookiesComponent from '@/components/Cookies';
import * as cookies from 'js-cookie';
import HeadComponent from "next/head";
import { Checktoken } from '../Utils/HealtCheck';

interface PokeHomeProps {
  children: React.ReactNode;
}

export default function PokeHome({ children }: PokeHomeProps) {
  Checktoken();
  
  if (sessionStorage.getItem('token') == null && cookies.default.get('token') == null) {
    // Redireccionar al usuario a la página de login si no tiene token
    window.location.href = '/login';
    // Puedes retornar null o cualquier otro contenido mientras se redirige
    return null;
  }
    return (
        <div>
        <HeadComponent>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pro.ico" />
        </HeadComponent>
        <div>
          <SetHome />
        </div>
        <CookiesComponent />
        {children}
      </div>
    );
  }