'use client'
import 'app/global.css'
import Head from "next/head";
import SetHome from "@/components/SetHome";
import Cookies from '@/components/Cookies';

export default function PokeHome({children}) {
    return (
        <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pro.ico" />
        </Head>
        <div>
          <SetHome />
        </div>
        <Cookies />
      </div>
    );
  }