import SignIn from "@/components/SignUp";
import Head from "next/head";

export default function Subscribe() {
    return (
        <div className="my-component">
          <Head>
            <meta name="description" content="Generated by create next app" />
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap"
          rel="stylesheet"/>
          </Head>
          <SignIn />
        </div>
      );
    }